# Generated by Django 3.2.8 on 2021-11-09 08:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_venue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
